/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ReactionList.java
 *
 * Created on 17-lug-2011, 11.23.30
 */
package it.freedomotic.plugins.gui;

import it.freedomotic.persistence.ReactionPersistence;
import it.freedomotic.plugins.AutomationsEditor;
import it.freedomotic.reactions.Command;
import it.freedomotic.reactions.Reaction;
import it.freedomotic.reactions.Trigger;
import it.freedomotic.util.PropertiesPanel_1;
import it.freedomotic.util.ReactionEditor;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;

/**
 *
 * @author Enrico
 */
public final class ReactionList extends javax.swing.JFrame {

    private AutomationsEditor plugin;
    private PropertiesPanel_1 pnlAutomations;

    /**
     * Creates new form ReactionList
     */
    public ReactionList(AutomationsEditor plugin) {
        initComponents();
        btnDelete.setEnabled(false);
        this.plugin = plugin;
    }

    private void populateEditor(Reaction selected) {
        JFrame frame = new JFrame("this is a test");
        frame.setLayout(new BorderLayout());
        ReactionEditor editor = new ReactionEditor(selected);
        frame.setPreferredSize(new Dimension(400, 30));
        frame.add(editor);
        frame.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstReactions = new javax.swing.JList();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Current Reactions");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Currently available automations:");

        jScrollPane1.setViewportView(lstReactions);

        btnDelete.setText("Delete Reaction");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDelete)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        updateData();
    }//GEN-LAST:event_formWindowActivated

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        Reaction rea = (Reaction) lstReactions.getSelectedValue();
        ReactionPersistence.remove(rea);
        updateData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        plugin.stop();
    }//GEN-LAST:event_formWindowClosing

    protected void updateData() {
        DefaultListModel model = new DefaultListModel();
        model.clear();
        for (Reaction rea : ReactionPersistence.getReactions()) {
            model.addElement(rea);
        }
        lstReactions.setModel(model);
        lstReactions.addListSelectionListener(new ListSelectionListener() {

            public void valueChanged(ListSelectionEvent e) {
                Reaction selected = (Reaction) lstReactions.getSelectedValue();
                if (selected != null) {
                    populateEditor(selected);
                    btnDelete.setEnabled(true);
                } else {
                    btnDelete.setEnabled(false);
                }
            }
        });
    }

    protected void setTargetTrigger(Trigger t) {
    }

    protected void setTargetCommand(Command c) {
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList lstReactions;
    // End of variables declaration//GEN-END:variables
}
