Document: freedomotic
Title: Debian freedomotic Manual
Author: <insert document author here>
Abstract: This manual describes what freedomotic is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freedomotic/freedomotic.sgml.gz

Format: postscript
Files: /usr/share/doc/freedomotic/freedomotic.ps.gz

Format: text
Files: /usr/share/doc/freedomotic/freedomotic.text.gz

Format: HTML
Index: /usr/share/doc/freedomotic/html/index.html
Files: /usr/share/doc/freedomotic/html/*.html
